// Public API du module `settings`.
// Tout import depuis l'extérieur (app/, autres modules autorisés) doit passer
// par ce fichier.
export {
  updatePasswordWithReauthAction,
  updateProfileAction,
  updateAccountEmailAction,
  uploadAvatarAction,
  updateAvatarColorAction,
  removeAvatarAction,
  deleteAccountAction,
  updateBillingAction,
  getNotificationSettings,
  updateNotificationSettingsAction,
  type PasswordChangeResult,
  type ProfileUpdateResult,
  type BillingUpdateResult,
  type AccountEmailChangeResult,
  type AvatarUploadResult,
  type AvatarColorChangeResult,
  type AvatarRemoveResult,
  type DeleteAccountResult,
  type NotificationSettings,
  type NotificationSettingsResult,
} from "./server/actions";

export {
  passwordChangeSchema,
  profileUpdateSchema,
  accountEmailChangeSchema,
  avatarColorChangeSchema,
  billingUpdateSchema,
  deleteAccountSchema,
  notificationSettingsUpdateSchema,
  SIRET_LENGTH,
  ACCOUNT_DELETION_CONFIRMATION_PHRASE,
  AVATAR_MAX_BYTES,
  AVATAR_ALLOWED_MIME,
  AVATAR_COLOR_PALETTE,
  DEFAULT_AVATAR_COLOR,
  BIO_MAX_LENGTH,
  USERNAME_MIN_LENGTH,
  USERNAME_MAX_LENGTH,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CHANNELS,
  DEFAULT_CHANNEL_ENABLED,
  isAllowedAvatarMime,
  isAllowedAvatarColor,
  type PasswordChangeInput,
  type ProfileUpdateInput,
  type AccountEmailChangeInput,
  type AvatarColorChangeInput,
  type AvatarColor,
  type DeleteAccountInput,
  type NotificationCategory,
  type NotificationChannel,
  type NotificationSettingsUpdateInput,
  type BillingUpdateInput,
} from "./lib/validation";
