import type { Resource, Template, ResourceItem } from '../types';

export const mockResources: Resource[] = [
  {
    category: 'resource',
    slug: 'creer-systeme-veille-notion',
    titre: 'Créer un système de veille avec Notion',
    description: 'Apprenez à construire un système de veille informationnelle complet dans Notion pour rester à jour dans votre domaine sans perdre de temps.',
    formation: 'Notion Architecte',
    type: 'Production',
    dateCreation: '2026-01-15T10:00:00.000Z',
    content: [
      { type: 'heading', level: 2, text: 'Pourquoi une veille structurée dans Notion ?' },
      { type: 'paragraph', text: 'La veille informationnelle est essentielle pour tout consultant Notion qui veut rester pertinent. Sans système, les informations s\'accumulent dans des onglets oubliés, des newsletters non lues et des favoris jamais revisités.' },
      { type: 'paragraph', text: 'Notion permet de centraliser toutes ces sources en un seul endroit et d\'en extraire de la valeur concrète pour vos clients.' },
      { type: 'tella_embed', url: 'https://www.tella.tv/video/mock-video-id' },
      { type: 'heading', level: 3, text: 'Les composants du système' },
      { type: 'list', items: [
        'Une base de données Articles avec statut de traitement',
        'Un inbox pour capturer rapidement les nouvelles informations',
        'Des filtres par thématique et par date',
        'Une vue Kanban pour gérer le flux de traitement',
        'Des templates de notes de synthèse',
      ]},
      { type: 'paragraph', text: 'La clé est de ne jamais laisser la base de données devenir un cimetière d\'articles. Chaque entrée doit avoir un statut clair : À lire, En cours, Traité, Archivé.' },
    ],
  },
  {
    category: 'resource',
    slug: 'structurer-offre-conseil-notion',
    titre: 'Structurer son offre de conseil Notion',
    description: 'Découvrez comment définir et présenter votre offre de services en tant que consultant Notion pour attirer les bons clients et maximiser votre valeur perçue.',
    formation: 'Notion Architecte',
    type: 'Relation Client',
    dateCreation: '2026-01-22T10:00:00.000Z',
    content: [
      { type: 'heading', level: 2, text: 'Définir son positionnement de consultant Notion' },
      { type: 'paragraph', text: 'Avant de parler tarifs et prestations, il faut clarifier à qui vous vous adressez et quel problème précis vous résolvez. Un positionnement flou génère des prospects mal qualifiés et des missions sous-payées.' },
      { type: 'paragraph', text: 'Le consultant Notion généraliste n\'existe plus vraiment sur un marché mature. Les clients recherchent des experts sur leur secteur ou leur cas d\'usage spécifique.' },
      { type: 'heading', level: 3, text: 'Les trois niveaux d\'offre' },
      { type: 'list', items: [
        'Audit Notion : diagnostic de l\'existant, 2-4h, livrable écrit',
        'Sprint d\'implémentation : mise en place d\'un système clé en main, 1-3 jours',
        'Accompagnement sur durée : formation de l\'équipe + itérations, 3-6 mois',
      ]},
      { type: 'paragraph', text: 'Chaque niveau correspond à un stade de maturité client différent. L\'audit est souvent la porte d\'entrée vers des missions plus longues.' },
    ],
  },
  {
    category: 'resource',
    slug: 'automatiser-processus-client',
    titre: 'Automatiser les processus client avec Notion',
    description: 'Utilisez les automatisations natives de Notion et les intégrations Zapier/Make pour créer des flux de travail client qui tournent sans intervention manuelle.',
    formation: 'Notion Architecte',
    type: 'Acquisition',
    dateCreation: '2026-02-03T10:00:00.000Z',
    content: [
      { type: 'heading', level: 2, text: 'L\'automatisation au service de l\'acquisition client' },
      { type: 'paragraph', text: 'L\'acquisition client est souvent le premier goulot d\'étranglement pour un consultant indépendant. Entre les relances, les devis, les onboardings — chaque étape prend du temps précieux.' },
      { type: 'tella_embed', url: 'https://www.tella.tv/video/mock-video-id' },
      { type: 'heading', level: 3, text: 'Ce qu\'on peut automatiser avec Notion' },
      { type: 'list', items: [
        'Envoi automatique d\'emails de suivi à l\'entrée d\'un prospect dans la base',
        'Création d\'un espace client dédié à la signature du contrat',
        'Notifications d\'équipe à chaque changement de statut d\'opportunité',
        'Synchronisation des contacts avec votre outil email marketing',
        'Rappels automatiques pour les relances prospects inactifs',
      ]},
      { type: 'paragraph', text: 'Notion Automatisations (natives) couvre les cas simples. Pour les flux complexes multi-outils, Make.com reste la solution la plus flexible avec un plan gratuit généreux.' },
    ],
  },
  {
    category: 'resource',
    slug: 'piloter-business-avec-notion',
    titre: 'Piloter son business avec Notion',
    description: 'Créez un tableau de bord central pour suivre vos finances, vos projets clients et vos objectifs de croissance depuis un seul espace Notion.',
    formation: 'Notion Business',
    type: 'Business',
    dateCreation: '2026-02-14T10:00:00.000Z',
    content: [
      { type: 'heading', level: 2, text: 'Un OS pour votre business dans Notion' },
      { type: 'paragraph', text: 'Notion peut devenir le véritable système d\'exploitation de votre activité. Pas juste un outil de notes, mais le endroit où vivent vos KPIs, vos projets, vos clients et votre vision.' },
      { type: 'paragraph', text: 'L\'objectif est d\'avoir une vue hebdomadaire qui vous donne en 5 minutes l\'état complet de votre business sans ouvrir 10 onglets différents.' },
      { type: 'heading', level: 3, text: 'Les 4 bases essentielles' },
      { type: 'list', items: [
        'Finances : revenus, dépenses, projections mensuelles',
        'Clients : statut, valeur contrat, prochaine action',
        'Projets : roadmap, jalons, livrables',
        'Objectifs : OKRs trimestriels avec suivi hebdomadaire',
      ]},
      { type: 'paragraph', text: 'Les relations entre ces bases font toute la magie : en cliquant sur un client, vous voyez immédiatement ses projets associés, les factures en cours et les prochaines échéances.' },
    ],
  },
  {
    category: 'resource',
    slug: 'gerer-equipe-commerciale-notion',
    titre: 'Gérer son équipe commerciale avec Notion',
    description: 'Implémentez un système de management commercial dans Notion pour suivre les performances, aligner l\'équipe et atteindre vos objectifs de vente.',
    formation: 'Notion Business',
    type: 'Sales',
    dateCreation: '2026-02-28T10:00:00.000Z',
    content: [
      { type: 'heading', level: 2, text: 'Pourquoi Notion pour le management commercial ?' },
      { type: 'paragraph', text: 'Les CRM traditionnels sont puissants mais souvent rigides et coûteux pour des équipes de moins de 10 personnes. Notion offre la flexibilité nécessaire pour adapter le système à votre cycle de vente spécifique.' },
      { type: 'paragraph', text: 'L\'avantage majeur : tout le contexte d\'une opportunité — emails, notes de réunion, contrats, propositions — peut vivre dans la même page que la fiche prospect.' },
      { type: 'heading', level: 3, text: 'Structure recommandée pour une équipe commerciale' },
      { type: 'list', items: [
        'Pipeline Notion avec étapes personnalisées selon votre cycle de vente',
        'Fiche prospect standardisée avec template d\'onboarding',
        'Dashboard individuel par commercial avec ses KPIs',
        'Vue manager avec comparaison des performances d\'équipe',
        'Reporting mensuel automatisé avec les formules Notion',
      ]},
      { type: 'paragraph', text: 'Pour les équipes qui ont déjà un CRM en place, Notion peut jouer le rôle de couche de collaboration : réunions d\'équipe, one-on-ones, partage de bonnes pratiques.' },
    ],
  },
  {
    category: 'resource',
    slug: 'construire-crm-client-notion',
    titre: 'Construire un CRM client dans Notion',
    description: 'Guide complet pour créer un CRM sur mesure dans Notion qui centralise toutes les informations clients et facilite le suivi des relations commerciales.',
    formation: 'Notion Business',
    type: 'Relation Client',
    dateCreation: '2026-03-10T10:00:00.000Z',
    content: [
      { type: 'heading', level: 2, text: 'Les fondations d\'un CRM Notion efficace' },
      { type: 'paragraph', text: 'Un CRM Notion bien conçu repose sur trois bases de données interconnectées : Contacts, Entreprises et Interactions. Cette structure en étoile permet de naviguer facilement entre les différents niveaux de relation.' },
      { type: 'paragraph', text: 'La clé est de définir dès le départ quelles informations sont réellement utiles au quotidien. Un CRM trop complexe n\'est jamais mis à jour — et un CRM pas mis à jour ne sert à rien.' },
      { type: 'heading', level: 3, text: 'Propriétés indispensables d\'une fiche contact' },
      { type: 'list', items: [
        'Statut de la relation (Prospect, Client actif, Client inactif, Partenaire)',
        'Valeur totale des contrats signés (formule calculée)',
        'Date du dernier contact et prochain rappel',
        'Source d\'acquisition (LinkedIn, Recommandation, Inbound)',
        'Tags personnalisés selon votre secteur',
      ]},
      { type: 'paragraph', text: 'N\'oubliez pas d\'intégrer un système de rappels : Notion peut envoyer des notifications automatiques quand une date de relance approche.' },
    ],
  },
];

export const mockTemplates: Template[] = [
  {
    category: 'template',
    slug: 'template-suivi-mission',
    titre: 'Template Suivi de Mission',
    description: 'Un espace complet pour piloter une mission de conseil Notion : brief client, livrables, suivi des heures et reporting final.',
    type: 'Pour les consultants Notion',
    urlTella: 'https://www.tella.tv/video/mock-template-1',
    urlNotionPublicPage: 'https://notion.so/templates/suivi-mission',
    dateCreation: '2026-01-10T10:00:00.000Z',
  },
  {
    category: 'template',
    slug: 'template-crm-client',
    titre: 'Template CRM Client',
    description: 'Un CRM léger et efficace pour gérer vos prospects et clients : pipeline de vente, fiches contact et suivi des interactions.',
    type: 'Pour les consultants Notion',
    urlTella: 'https://www.tella.tv/video/mock-template-2',
    urlNotionPublicPage: 'https://notion.so/templates/crm-client',
    dateCreation: '2026-01-20T10:00:00.000Z',
  },
  {
    category: 'template',
    slug: 'template-second-cerveau',
    titre: 'Template Second Cerveau',
    description: 'Un système de gestion des connaissances inspiré de la méthode PARA pour capturer, organiser et retrouver toutes vos informations.',
    type: 'Système Généraliste',
    urlNotionPublicPage: 'https://notion.so/templates/second-cerveau',
    dateCreation: '2026-02-05T10:00:00.000Z',
  },
  {
    category: 'template',
    slug: 'template-dashboard-perso',
    titre: 'Template Dashboard Personnel',
    description: 'Un tableau de bord de vie pour suivre vos objectifs, habitudes, finances et projets personnels depuis un seul endroit.',
    type: 'Système Généraliste',
    urlTella: 'https://www.tella.tv/video/mock-template-3',
    urlNotionPublicPage: 'https://notion.so/templates/dashboard-perso',
    dateCreation: '2026-02-18T10:00:00.000Z',
  },
];

export const mockResourceItems: ResourceItem[] = [
  ...mockResources,
  ...mockTemplates,
];
