// Public API du module `community`.
export { CommunityPage } from "./routes/community-page";
export { CommunityPostDetailPage } from "./routes/community-post-detail-page";
export { CommunityRestrictedPage } from "./routes/community-restricted-page";

// Server (queries + actions)
export {
  listPosts,
  getPostById,
  listCommentsForPost,
  listConversations,
  getConversation,
  mapProfileMember,
  type CommunityMember,
} from "./server/queries";
export {
  createPostAction,
  updatePostAction,
  deletePostAction,
  uploadPostMediaAction,
  uploadDmFileAction,
  deletePostMediaAction,
  listMembersAction,
  createCommentAction,
  updateCommentAction,
  deleteCommentAction,
  createCommentReplyAction,
  updateCommentReplyAction,
  deleteCommentReplyAction,
  togglePostReactionAction,
  toggleCommentReactionAction,
  toggleCommentReplyReactionAction,
  createConversationAction,
  sendMessageAction,
  markConversationReadAction,
  editMessageAction,
  deleteMessageAction,
  toggleMessageReactionAction,
  forwardMessageAction,
  getUserTopEmojisAction,
  type CreatePostResult,
  type UpdatePostResult,
  type DeletePostResult,
  type UploadPostMediaResult,
  type UploadDmFileResult,
  type DeletePostMediaResult,
  type CreateCommentResult,
  type UpdateCommentResult,
  type DeleteCommentResult,
  type CreateCommentReplyResult,
  type UpdateCommentReplyResult,
  type DeleteCommentReplyResult,
  type ToggleReactionResult,
  type CreateConversationResult,
  type SendMessageResult,
  type MarkConversationReadResult,
  type EditMessageResult,
  type DeleteMessageResult,
  type ToggleMessageReactionResult,
  type ForwardMessageResult,
  type GetUserTopEmojisResult,
} from "./server/actions";

// Validation (zod + constants)
export {
  createPostSchema,
  updatePostSchema,
  createCommentSchema,
  updateCommentSchema,
  createCommentReplySchema,
  updateCommentReplySchema,
  togglePostReactionSchema,
  toggleCommentReactionSchema,
  toggleCommentReplyReactionSchema,
  createConversationSchema,
  sendMessageSchema,
  markConversationReadSchema,
  editMessageSchema,
  deleteMessageSchema,
  toggleMessageReactionSchema,
  forwardMessageSchema,
  MESSAGE_BODY_MIN,
  MESSAGE_BODY_MAX,
  MESSAGE_TYPES,
  REPLY_SNIPPET_MAX,
  FORWARD_MAX_TARGETS,
  POST_TAGS,
  POST_AUDIENCES,
  POST_TITLE_MIN,
  POST_TITLE_MAX,
  POST_BODY_MIN,
  POST_BODY_MAX,
  COMMENT_BODY_MIN,
  COMMENT_BODY_MAX,
  POST_MEDIA_ALLOWED_MIME,
  POST_MEDIA_MAX_BYTES,
  isAllowedPostMediaMime,
  DM_FILE_ALLOWED_MIME,
  DM_FILE_MAX_BYTES,
  isAllowedDmFileMime,
  type CreatePostInput,
  type UpdatePostInput,
  type CreateCommentInput,
  type UpdateCommentInput,
  type CreateCommentReplyInput,
  type UpdateCommentReplyInput,
  type TogglePostReactionInput,
  type ToggleCommentReactionInput,
  type ToggleCommentReplyReactionInput,
  type CreateConversationInput,
  type SendMessageInput,
  type MarkConversationReadInput,
  type EditMessageInput,
  type DeleteMessageInput,
  type ToggleMessageReactionInput,
  type ForwardMessageInput,
  type MessageType,
  type PostMediaMimeType,
} from "./lib/validation";

export type { User, Role, Offer } from "./types/user.types";
export type { Post, PostTag, PostAudience } from "./types/post.types";
export type { Comment, CommentReply } from "./types/comment.types";
export type { Conversation, Message } from "./types/conversation.types";
export type { Notification } from "./types/notification.types";
